---
- name: Deploy SOC Defender Pipeline
  hosts: soc_nodes
  become: yes
  vars_files:
    - secrets.yml

  tasks:
    - name: install dependencies
      ansible.builtin.apt:
        name:
          - nginx
          - curl
          - git
        state: present
        update_cache: yes

    - name: Reverse proxy Nginx
      ansible.builtin.copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              location / {
                  proxy_pass http://127.0.0.1:8080;
              }
          }
      notify: restart nginx

    - name: Download docker installer
      ansible.builtin.get_url:
        url: "https://get.docker.com"
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Execute Docker installer
      ansible.builtin.command: /tmp/get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Clone the SOC repo
      ansible.builtin.git:
        repo: "git@github.com:ape322/soc-defender-lab.git"
        dest: /opt/soc-defender-lab
        version: main
        key_file: /home/max/.ssh/soc_deploy
        accept_hostkey: yes
        force: yes

    - name: Injest encrypted dis webhook
      ansible.builtin.copy:
        dest: /opt/soc-defender-lab/.env
        content: "DISCORD_WEBHOOK={{ discord_webhook }}\n"
        mode: '0600'

    - name: Create a folder with logs
      ansible.builtin.copy:
        content: "[]\n"
        dest: /var/log/soc_threat_ledger.json
        mode: '0640'

    - name: Tear down existing pipeline
      ansible.builtin.command: docker compose down
      args:
        chdir: /opt/soc-defender-lab

    - name: Docker compose
      ansible.builtin.command: docker compose up -d --build
      args:
        chdir: /opt/soc-defender-lab

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
